name: Check outdated FAQ

on:
  schedule:
    - cron: '0 3 1 */2 *' # every 1st day every 2 months at 03:00 UTC
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm ci --ignore-scripts --no-audit --no-fund
      - run: npx ts-node scripts/checkOutdatedFaq.ts 