name: Update Market Rates

on:
  schedule:
    - cron: '0 3 * * 1'
    - cron: '0 4 1,15 * *'
  workflow_dispatch:

jobs:
  fetch:
    runs-on: ubuntu-latest
    env:
      SEARATES_KEY: ${{ secrets.SEARATES_KEY }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install
        run: npm install -g pnpm && pnpm install --frozen-lockfile
      - name: Run priority lanes (weekly)
        if: ${{ github.event.schedule == '0 3 * * 1' || github.event_name == 'workflow_dispatch' }}
        run: pnpm ts-node scripts/fetchMarketRates.ts
      - name: Run secondary lanes (1st and 15th)
        if: ${{ github.event.schedule == '0 4 1,15 * *' }}
        run: pnpm ts-node scripts/fetchMarketRates.ts --secondary
      - name: Commit & push
        run: |
          git config user.name "market-bot"
          git config user.email "bot@olv.com"
          git add data/market_rates.json || true
          git commit -m "chore: automated market rates update" || echo "No changes"
          git push || echo "No changes to push" 